### ISSUE TITLE
您好我想把这个插件发布到mcbbs上可以吗

### ISSUE THREAD

**Issue by 3186418613** [unionofblackbean/UBBDispenserShulkerBoxCrashFixer#2]
您好请问我想把这个插件发布到mcbbs上可以吗
www.mcbbs.net

**Comment by Ahuang666** [comment]
+1+1

**Comment by leungyauming** [comment]
可以 你可以任意轉發
但請標注作者是小豆黑服/Union of Black Bean

**Comment by N14777787289** [comment]
原帖地址在哪里啊


> 您好请问我想把这个插件发布到mcbbs上可以吗
> [www.mcbbs.net](http://www.mcbbs.net)

**Comment by Fluair** [comment]
转载贴在哪里啊，求链接

> 您好请问我想把这个插件发布到mcbbs上可以吗
> [www.mcbbs.net](http://www.mcbbs.net)
